### ISSUE TITLE
A question about dedUCE

### ISSUE THREAD

**Issue by ueda0818** [slimsuite/deduce#2]
Dear author, I have a question about how to succeed my analysis. I make a directory named "deduce" and download three genomes from NCBI. Then, I  entered the following command, but it did not work correctly.

```
(base) yk8@yk8 dedUCE-result % deduce find \
  --jf-hash-size 20G \
  --threads 8 \
  --uce-max-occurrences 100 \
  --uce-min-length 200 \
  --uce-core-min-homology 1 \
  --output deduce_1.0.0_uces_bej04 \
  --core-kmer-threshold 1 \
  --core-kmer-size 50 \
  --mapper minimap \
  --debug \
  /Volumes/BigDataStorage/Lab_People/UEDA/dedUCE
[2024-10-17 16:29:1729150141] [250] Core: starting search for core kmers...
[2024-10-17 16:29:1729150141] [250] Core: hashing genomes...
[2024-10-17 16:29:1729150141] [250] Core: reducing hash counts...
[2024-10-17 16:29:1729150141] [250] Core: intersecting hashes...
Traceback (most recent call last):
  File "/Users/yk8/miniconda3/bin/deduce", line 8, in <module>
    sys.exit(main())
  File "/Users/yk8/miniconda3/lib/python3.8/site-packages/deduce_uces/main.py", line 154, in main
    run_find(args, logger)
  File "/Users/yk8/miniconda3/lib/python3.8/site-packages/deduce_uces/main.py", line 73, in run_find
    core_kmers = find_core_kmers(genomes, args, context)
  File "/Users/yk8/miniconda3/lib/python3.8/site-packages/deduce_uces/stages/core.py", line 82, in find_core_kmers
    hash_params,
UnboundLocalError: local variable 'hash_params' referenced before assignment
```
Below is the "dedUCE" directory structure.

```
dedUCE
├── MADL_Memer_1.fasta
├── UMN_Dpol_1.fasta
└── xbMytCali10p.fasta
```

Do you know why this happened?

**Comment by cabbagesofdoom** [comment]
Hi. I'm afraid the main developer has moved on to other things, but I will try to help if I can. Did you try running first without the `--debug` command? Can you include the accession numbers of the three genomes and I will see if I can recreate the error. Thanks, Rich

**Comment by ueda0818** [comment]
Thank you for your reply. 

I have tried without the `--debug` but have gotten the same result.

The following three genome accession numbers were used.

GCA_021730395.1
GCA_020536995.1
GCA_021869535.1

These are _Mercenaria mercenaria_, _Dreissena polymorpha_, and _Mytilus californianus_.

I'm sorry for the trouble.

**Comment by cabbagesofdoom** [comment]
I'm sorry it's not working! I think there might be some trickiness getting the dependencies installed, so I'd like to get it containerised really. Do you have a record of how you installed it and its dependencies?

**Comment by ueda0818** [comment]
Hi. I tried reinstalling the dependencies but noticed that I couldn't completely install jellyfish. I'll challenge it.
Thank you for your support.

**Comment by ueda0818** [comment]
> I'm sorry it's not working! I think there might be some trickiness getting the dependencies installed, so I'd like to get it containerised really. Do you have a record of how you installed it and its dependencies?

Hi, I'm sorry, but I couldn't get it to work. I’m using an iMac (27-inch, 3.8 GHz 8-core 10th-generation Intel Core i7 processor, 64 GB memory). I created a virtual environment and installed dedUCE, Jellyfish, Samtools, and Minimap2 according to the manual, but I got the same result.

**Comment by mpx-mdx** [comment]
I had the same problem:
UnboundLocalError: local variable 'hash_params' referenced before assignment

**Comment by nicolasmalexandre** [comment]
Im having the same issue

**Comment by jdamas13** [comment]
Make sure your genome files end in '.fa'. This extension is hardcoded when searching for genomes, so if your files have any other fasta extension they won't be found. As a consequence, hash_params will be empty and that error shown.

**Comment by slimsuite** [comment]
@jdamas13 thanks so much for that reply. I had forgotten about that constraint.

@mpx-mdx and @nicolasmalexandre can you let me know if that fixes the issue for you?
